language: python
python:
  - "2.6"
  - "2.7"
# command to install package
install:
  - pip install setuptools --upgrade
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - balert
after_success:
  coveralls
notifications:
  email: false
